### ISSUE TITLE
Custom capes don't show for some reason

### ISSUE THREAD

**Issue by JimmyJxt** [GeyserMC/ThirdPartyCosmetics#8]
https://dump.geysermc.org/4rMd1qsuop9OAtRJFByVRnS9pZaDhboF

**Comment by rtm516** [comment]
Can you provide information about the cape?
- Confirm your expecting it to show on a java player from a bedrock client
- Copy of the texture
- Provider it's on
- Account name it's attached to

**Comment by 200Tigersbloxed** [comment]
I'll add on to this.

1. I can confirm that the Bedrock client is awaiting a cape on a Java player by adding simple debugging
2. [Cape Link](https://optifine.net/capes/200Tigersbloxed.png)
3. Optifine
4. `200Tigersbloxed`

Here's some screenshots

![image](https://github.com/user-attachments/assets/8f618f91-a101-4511-bea7-f76888a8bee0)
![image](https://github.com/user-attachments/assets/d068438a-1c4b-4391-993b-621011c911b5)
![image](https://github.com/user-attachments/assets/836185b8-2914-40ca-ba6e-9970cfd52e38)

I've also tried this in numerous environments. Velocity, Paper, and Paper with only two plugins (`Geyser-Spigot` and `floodgate-spigot`).

**Comment by 200Tigersbloxed** [comment]
I have found the problem. Optifine capes are `92x44`, whereas [regular capes](https://gamepedia.cursecdn.com/minecraft_pl_gamepedia/9/9a/Minecon_Cape2012.png) are `64x32`. After resizing the Optifine cape, it actually loads. It's just offset and looks odd.

![image](https://github.com/user-attachments/assets/5d8c73b5-96ea-41f9-833b-877b20c153d8)

**Comment by 200Tigersbloxed** [comment]
And, tada! After reimporting the [old scaling code](https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java#L441), it now works great!

![image](https://github.com/user-attachments/assets/40a2f87e-41c0-4dae-af14-c1b823cc7874)

If you'd like, I can open a PR for this fix or attach a build if further investigation is needed. However, this issue should be renamed as it is now known what causes this issue! (and what the fix is)

**Comment by rtm516** [comment]
Thanks for looking into this @200Tigersbloxed 

More than happy for you to open a PR fixing the scaling issue.
